export const BASE_URL = 'http://backend-test.bazar365.com/api/';
export const IMAGE_URL = "https://bazar365-test.sgp1.digitaloceanspaces.com/"

export const EMPLOYEE_API = BASE_URL + "user/employees"
export const REQUIREMENTS_API  = BASE_URL + "requirements"
export const GENERALSETTINGS_API  = BASE_URL + "generalSetting"
export const PRODUCTSGROUP_API  = BASE_URL + "productGroup"
export const ADDRESS_API  = BASE_URL + "addressGroup"
export const DELIVERYGROUP_API  = BASE_URL + "deliveryGroup"
export const ORDERS_API = BASE_URL + "orders"
export const CUSTOMERS_API = BASE_URL + "user/customers"
export const PACKAGES_API = BASE_URL + "promo/packages"
export const PROMOCODE_API = BASE_URL + "promo/promoCodes"
export const PROMOCODETYPE_API = BASE_URL + "promo/promoCodeTypes"
export const PACKAGEPRODUCT_API = BASE_URL + "promo/packageProducts"
export const PAYMENTTYPE_API = BASE_URL + "paymentTypes"
